### ISSUE TITLE
Crash when starting game

### ISSUE THREAD

**Issue by magcicada** [Droog71/ReactorTurbines#1]
This is crash report:[https://pastebin.com/12fpaqYG](https://pastebin.com/12fpaqYG)

**Comment by Droog71** [comment]
Thanks for reporting this! I did some research into why I keep having issues with java.lang.NoSuchFieldError in relation to block materials and the best information I could find is that the Forge version I am using to develop the mod differs from the version used to run the mod. So, I've updated my dev environment to Forge 14.23.5.2854 and reverted the turbine block material to Material.IRON. Hopefully this takes care of the problem. If the problem does not reoccur after some time, I will close this issue.
