### ISSUE TITLE
block breaks instantly, and no recipe with either ic2

### ISSUE THREAD

**Issue by Trinsdar** [Droog71/ReactorTurbines#2]
probably cause you do this:
[https://github.com/Droog71/ReactorTurbines/blob/master/main/resources/assets/reactor_turbines/recipes/turbine_impeller_recipe.json#L9](https://github.com/Droog71/ReactorTurbines/blob/master/main/resources/assets/reactor_turbines/recipes/turbine_impeller_recipe.json#L9)
instead of doing separate jsons that use forge conditional checks for which one gets loaded

**Comment by Droog71** [comment]
Thanks for the report. All fixed now.
https://www.curseforge.com/minecraft/mc-mods/reactor-turbines-mod-for-ic2/files/3072310
